### ISSUE TITLE
USER STORY: Initial Django Setup MS1

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#1]
As a **developer** I can **setup a new Django project** so that **I can create the project's structure**

## Tasks:
- [x] Install Django through the package manager
- [x] Create new project with the name AutoMarket
- [x] Create the first app and add it to settings.py
- [x] Create env.py file to hide the secret keys
- [x] Add env.py to .gitignore so that the secret keys stay private

**Comment by Dayana-N** [comment]
Completed
