### ISSUE TITLE
USER STORY: User Password Reset MS3

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#10]
As a **registered user** I want to **be able to reset my password** so that I can **regain access to my account in case I forget my password**

## Acceptance Criteria 

- Given I am a registered user, When I am on the login page, Then I should see a "Forgot Password" link.
- Given I am a registered user and I click on the "Forgot Password" link, When I am redirected to the password reset page, Then I should see a form where I can enter my email address to initiate the password reset process.
- Given I am a registered user and I enter my email address on the password reset page, When I submit the form, Then I should receive an email with instructions on how to reset my password.
- Given I am a registered user and I enter a new password on the password reset page, When I submit the form, Then my password should be successfully reset, and I should receive a confirmation message.

## Tasks

- [x] Implement forgot password link on the login page.
- [x] Create url for reset password, email sent, enter new password and password changed successfully
- [x] Create templates for reset password, email sent, enter new password and password changed successfully

**Comment by Dayana-N** [comment]
completed
