### ISSUE TITLE
USER STORY: View my listings MS4

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#19]
As a **registered user** I want to **be able to see all of the listings I have created** so that I can **manage and keep track of the vehicles I have listed for sale.** 
## Acceptance Criteria:

- Given I am a registered user, When I am logged in to my account, Then I should see a "My Listings" link on my profile page.
- Given I am a registered user and I click on the "My Listings" link, When I am redirected to the "My Listings" page, Then I should see a list of all the listings I have created
- Given I am a registered user and I am on the "My Listings" page, When I click on a specific listing from the list, Then I should be redirected to the individual listing page where I can view the details of that particular listing.

## Tasks:
- [x] Implement the frontend template for the user's profile page, displaying the "My Listings" link.
- [x] Set up a URL pattern for the "My Listings" page, which displays a list of the user's created listings.
- [x] Create a template for the "My Listings" page to display the necessary details of each listing, allowing users to easily review their listings.
- [x] Implement backend logic to display the user's created listings on the "My Listings" page.

**Comment by Dayana-N** [comment]
Added dynamically using Javascript. One view renders profile, my listings and my favourites.
