### ISSUE TITLE
USER STORY: Connect database and media storage MS1

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#2]
As a **developer** I can **connect database and media storage** so that **the user's stored data is stored successfully**

## Tasks:
- [x] install required packages
- [x] Configure Django's settings to connect to database.
- [x] Configure setting for ElephantSQL
- [x] Configure settings for static files
- [x] Configure AWS settings
- [x] Configure Django's settings to connect to AWS. 
- [x] Run migrations.
- [x] Create superuser and run migrations again.
- [x] Test database and media storage (test model may be required)

**Comment by Dayana-N** [comment]
Connected to database and AWS.. Set settings for static files. Created test model and html page for testing purposes. 
Completed
