### ISSUE TITLE
USER STORY: View Favourite Listings MS7

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#26]
As a **registered user** I want to be able to **view my favourite listings** so that I can **easily revisit them later**

## Acceptance Criteria:

- Given I am a registered user and I have added listings to my favorites, When I navigate to the "Favorites" page from my profile, Then I should see a list of all the listings I have saved.
- Given I am a registered user and I am on the "Favorites" page, When I click on a specific listing from the list, Then I should be redirected to the individual listing page to view the full details of the listing.

## Tasks:
- [x] Implement the frontend template for the user's profile page, displaying the "My Favourites" link.
- [x] Set up a URL pattern for the "My Favourites" page, which displays a list of the user's saved listings.
- [x] Create a template for the "My Favourites" page to display the necessary details of each listing, allowing users to easily review their saved listings.
- [x] Implement backend logic to display the user's saved listings on the "My Favourites" page.

**Comment by Dayana-N** [comment]
completed
