### ISSUE TITLE
USER STORY: Initial deployment MS1

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#3]
As a **developer** I can **deploy the application early** so that ** I can confirm that the initial setup is working and can continue testing the application during development**

## Tasks:
- [x] Create new app on Heroku
- [x] Add all secret keys to config vars
- [x] Create requirements.txt file
- [x] Create Procfile
- [x] Deploy to Heroku and test if the application runs with no errors

**Comment by Dayana-N** [comment]
Deployment Successful. 
Completed
