### ISSUE TITLE
USER STORY: Navigation MS2

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#31]
As a **User** I can **navigate through the website** so that **I can access different sections efficiently**

## Acceptance Criteria:

- Given that I am on the website, When I access the navigation bar, Then I expect it to be prominently displayed at the top of the webpage.
- Given that I click on any link in the navigation bar, When I click the link, Then I am promptly redirected to the corresponding page without any delays or errors.
- Given that I access the website from different devices, When I view the navigation bar, Then I can effortlessly navigate through it, as the navigation bar is designed to be responsive

## Tasks: 
- [x] Design the navigation bar
- [x] Ensure the navigation bar is fully responsive
- [x] Ensure all links in the navigation bar redirect to the correct page.

**Comment by Dayana-N** [comment]
completed
