### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#32]
As a **user** I can **visit the home page** so that **I can quickly browse and find relevant car listings based on my preferences**

## Acceptance Criteria:

- Given that I visit the website, When I access the home page, Then I expect it to be visually appealing and easy to navigate
- Given that I visit the website on a mobile device, When I navigate to the home page, Then I expect it to be responsive and adapt to different screen sizes.
- Given that I visit the website, When I access the home page, Then I expect to be able to search car listings based on my preference
- Given that I visit the website, When I access the home page, Then I expect to be able to view the most recent listings

## Tasks:

- [x] Create appealing hero section, which is responsive on all devices
- [x] Create a search form to allow the user to search cars by preference
- [x] Create cards to display the most recent listings on the home page

**Comment by Dayana-N** [comment]
The search form was created. Functionality to be added with #21
