### ISSUE TITLE
USER STORY: User account page

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#35]
As a **non-authenticated user,** I want to **access the user profile pages of listing owners,** so that I can **view their contact details and listings.

## Acceptance Criteria

- Given I am a non-authenticated user, When I visit a listing owner's profile page, Then I should be able to see their contact details and listings.
- Given I am an authenticated user, When I visit my own profile page, Then I should be able to see my contact details, listings and favourites.

## Tasks 

- [x] Create the url path for the user's account.
- [x] Create html template to display the user's profile and listings
- [x] Create a view to retrieve the user's profile information from the database and pass this to the template
- [x] Add a link to the user account page to the seller's image on the single listing page. 
- [x] Modify the existing javascript code for my profile to fit the needs of the user's account page without throwing any errors

**Comment by Dayana-N** [comment]
completed

**Comment by Dayana-N** [comment]
Updated this issue, removed the favourites functionality as there is a separate ticket for this feature. During the process of development, a decision was made to render each page (my listings and my favourites) individually instead of dynamic using JavaScript. This was to avoid complications with pagination and users being redirected to the wrong page.

**Comment by Dayana-N** [comment]
This issue seems to be duplicate of View User's Profile MS3 #11
