### ISSUE TITLE
USER STORY: User Login MS3

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#8]
As a **registered user** I want **to be able to log in to my account **so I can **view my profile page, my listings and my favourites.**

## Acceptance Criteria
- Given I am a registered user, When I visit the login page, Then I should see a login form with input fields for username/email and password.
- Given I am a registered user and I enter valid login credentials, When I submit the login form, Then I should be successfully logged in to my account and redirected to my profile page or the landing page.
- Given I am a registered user and I enter invalid login credentials, When I submit the login form, Then I should receive an appropriate error message indicating that the login attempt was unsuccessful.
- Given I am a registered user When I am logged in, Then I should see logout button in the navbar instead of Login

## Tasks:
- [x] Design and implement the frontend template for the login page, providing fields for the username and password.
- [x] Set up a URL pattern and backend logic to handle the login form submission.
- [x] Redirect user to home page after login

**Comment by Dayana-N** [comment]
Completed
