### ISSUE TITLE
USER STORY: User Profile Page View/Edit MS3

### ISSUE THREAD

**Issue by Dayana-N** [Dayana-N/AutoMarket-PP4#9]
As a **registered user** I want to be able **to see my profile page** so that I can **update my information**

## Acceptance Criteria

- Given I am a registered user, When I log in to my account, Then I should be able to access my profile page.
- Given I am a registered user and I am on my profile page, Then I should see my personal information such as username, email, and profile picture.
- Given I am a registered user and I am on my profile page, When I update my information through the profile page, Then the changes should be saved and reflected on my profile.
- Given I am a registered user and I am on my profile page, When I click on the "Edit Profile" button, Then I should be able to edit my information.
- Given I am a registered user and I edit my information on the profile page, When I submit the updated information, Then the changes should be saved and applied to my profile, and I should receive a confirmation message.

## Tasks:
- [x] Define the profile url
- [x] Create the view that renders the profile page.
- [x] Create the option to edit the profile with prefilled details.
- [x] Create the view that handles the edit form.
- [x] Ensure there is an edit button on the profile page.

**Comment by Dayana-N** [comment]
Completed
